local out=assert(os.getenv('TMC_TEST_OUTPUT'))
local H=assert(loadfile(out..'../../tests/gameplay_harness.lua'))()
H.run(function()
 H.menu(27,0);H.option('actorFilter',0)
 H.press(0x40);H.shot('list_last_page')
 local cursor=H.r8(H.PM+H.L.cursor+27)
 H.check(cursor>=10,'up wraps to last entry on a second list page')
 H.press(1);H.check(H.r8(H.PM+H.L.page)==28,'last paginated entry opens details')
 H.press(2);H.check(H.r8(H.PM+H.L.page)==27 and H.r8(H.PM+H.L.cursor+27)==cursor,'back retains paginated list cursor')
 for f=1,7 do H.press(0x10);H.shot('filter_'..(f%7));H.check(H.r8(H.PM+H.L.actorFilter)==f%7,'filter cycle '..f) end
 H.option('actorFilter',1);H.wait(2);H.press(1)
 H.check(H.r8(H.PM+H.L.page)==27,'empty enemy list does not dereference an actor')
 H.press(0x10);H.check(H.r8(H.PM+H.L.actorFilter)==2,'empty list still accepts filter navigation')
 H.close();H.menu(29,0)
 local count=H.L.actorSpawnCount or 5
 H.press(0x20);H.check(H.r8(H.PM+H.L.actorSpawn)==count-1,'selection wraps to final catalog entry')
 H.press(0x10);H.check(H.r8(H.PM+H.L.actorSpawn)==0,'selection wraps to first catalog entry')
 if H.L.actorSpawnCount then
  H.press(0x100);H.check(H.r8(H.PM+H.L.actorSpawn)==5%count,'R jumps forward five entries')
  H.press(0x200);H.check(H.r8(H.PM+H.L.actorSpawn)==0,'L jumps backward five entries')
 end
 H.close()
 H.warp(0,0,504,504);H.openFloor();emu:write8(H.PM+16,1)
 H.menu(29,1);H.press(1);H.wait(90);H.close()
 local e=H.r32(H.PM+H.L.actorSelected);assert(e>=0x30015A0 and e<0x3003BE0,'native actor required')
 H.menu(28,1);H.press(1);H.press(1)
 H.check(H.r8(H.PM+H.L.page)==28 and H.r32(e+4)~=0,'default cancel preserves selected actor')
 -- Existing settings editor: confirmation START+A, remove default L and R.
 H.menu(13,6);H.press(1);H.menu(24,5);H.press(1);H.menu(24,6);H.press(1);H.menu(24,4);H.press(1);H.menu(24,7);H.press(1)
 H.check(H.r16(H.PM+H.L.confirmHotkey)==9,'custom confirmation applies through native menu input')
 H.menu(28,1);H.press(1);H.press(0x80);H.press(0x301)
 H.check(H.r8(H.PM+13)==1 and H.r32(e+4)~=0,'old default chord cannot delete after rebinding')
 H.shot('custom_remove_hotkey');H.press(9);H.wait(45);H.close()
 H.check(H.r32(H.PM+H.L.actorSelected)==0,'custom START+A deletes through guarded native path')
end)
