local out=assert(os.getenv('TMC_TEST_OUTPUT'))
local H=assert(loadfile(out..'../../tests/gameplay_harness.lua'))()
local function complete()
 H.menu(16,10);H.press(1);H.press(0x80);H.press(0x301);H.wait(220);H.close()
end
H.run(function()
 H.menu(16,11);H.press(1)
 H.check(H.r8(H.PM+H.L.page)==16,'undo without snapshot cannot open confirmation')
 H.close();local a,r=H.r8(H.R+4),H.r8(H.R+5)
 local x,y=H.r32(H.P+44),H.r32(H.P+48)
 -- Nonzero unused tail proves that the entire native 4B4-byte save is captured.
 emu:write32(0x2002A40+0x4AC,0x12345678)
 local original=emu:readRange(0x2002A40,0x4B4)
 complete()
 local backup=emu:readRange(H.PM+H.L.completionBackup,0x4B4)
 H.check(H.r8(H.PM+H.L.completionUndoValid)==1 and backup==original,'full native save including all quest timers captured byte-exactly')
 H.menu(16,11);H.shot('undo_ready');H.press(1);H.shot('undo_default_cancel')
 H.check(H.r8(H.PM+H.L.cursor+25)==0,'undo confirmation defaults to CANCEL')
 local completed=emu:readRange(0x2002A40,0x4B4);H.press(1)
 H.check(emu:readRange(0x2002A40,0x4B4)==completed,'undo CANCEL preserves completed save')
 complete();H.check(emu:readRange(H.PM+H.L.completionBackup,0x4B4)==backup,'repeated completion preserves FIRST backup')
 H.warp(0x23,7,120,120)
 local slot=H.r8(0x2000004);emu:write8(0x2000004,(slot+1)%3)
 H.menu(16,11);H.press(1);H.check(H.r8(H.PM+H.L.page)==16,'different save-slot identity blocks old backup')
 emu:write8(0x2000004,slot)
 H.menu(16,11);H.press(1);H.press(0x80);H.press(1)
 H.check(H.r8(H.PM+H.L.completionUndoValid)==1,'A alone cannot undo')
 H.option('resourceCheats',15);H.shot('undo_requires_confirmation');H.press(0x301)
 for i=1,180 do if H.r8(H.PM+H.L.completionUndoValid)==0 then break end;H.wait(1) end
 H.check(emu:readRange(0x2002A40,0x4B4)==backup,'undo restores EVERY save byte before native room initialization')
 H.check(H.r8(H.PM+H.L.resourceCheats)==0,'resource refill cheats disabled during restore')
 H.wait(200);H.close();H.shot('undo_restored_gameplay')
 H.check(H.r8(H.R+4)==a and H.r8(H.R+5)==r,'undo returns to original room after warping elsewhere')
 H.check(H.r32(H.P+44)==x and H.r32(H.P+48)==y,'original position restored')
 H.check(H.r8(0x2002A46)==0 and H.r8(0x2002AEB)==original:byte(0xAB+1),'credits and heart capacity restored after native reload')
 local px=H.r32(H.P+44);H.wait(12,0x20);H.wait(5)
 H.check(H.r32(H.P+44)~=px,'normal movement after undo')
 H.menu(16,11);H.press(1);H.check(H.r8(H.PM+H.L.page)==16,'consumed undo cannot be applied twice');H.close()
 complete();emu:reset();H.boot()
 H.check(H.r8(H.PM+H.L.completionUndoValid)==0,'real reset discards RAM backup')
 complete()
 -- Native file-select->game entry, same slot, without resetting EWRAM.
 H.log('FIXTURE same-slot native GameTask_Transition lifecycle')
 emu:write8(H.M+3,0);emu:write8(H.M+4,0);H.wait(180)
 H.check(H.r8(H.PM+H.L.completionUndoValid)==0,'native same-slot loading lifecycle invalidates old snapshot')
end)
