local out=assert(os.getenv('TMC_TEST_OUTPUT'))
local H=assert(loadfile(out..'../../tests/gameplay_harness.lua'))()
H.run(function()
 local area,room=H.r8(H.R+4),H.r8(H.R+5)
 local pos=emu:readRange(H.P+44,8)
 H.menu(21,0);H.shot('beta_category');H.press(1);H.wait(180);H.close()
 H.check(H.r8(H.R+4)==0x24 and H.r8(H.R+5)==0x1F,'native unused tree room loads')
 H.shot('unused_tree_room')
 local x=H.r32(H.P+44);H.wait(12,0x20);H.wait(8)
 H.check(H.r32(H.P+44)~=x and H.r8(H.P+0xC)==1,'unused room spawn permits normal movement')
 H.menu(21,2);H.press(1);H.check(H.item(5)==0,'unused sword info does not grant broken item')
 H.menu(21,1);H.press(1);H.wait(180);H.close();H.shot('return_from_unused_room')
 H.check(H.r8(H.R+4)==area and H.r8(H.R+5)==room,'dedicated beta return reaches original room')
 H.check(emu:readRange(H.P+44,8)==pos,'beta return preserves original position')
end)
